export type Question = {
	cards: number[];
	blacklist?: string;
  afterMessageHeading?: string;
  afterMessage?: string;
};
export const questions: Question[] = [
	{ cards: [5, 5, 1] },
	{ cards: [8, 2, 4] },
	{ cards: [6, 2, 6] },
	{ cards: [3, 4, 9] },
	{ cards: [5, 6, 9] },
	{ cards: [1, 3, 7] },
	{ cards: [2, 3, 6] },
	{ cards: [1, 4, 5] },
	{ cards: [1, 4, 7] },
	{ cards: [2, 5, 7] },
	{ cards: [3, 5, 9] },
	{ cards: [6, 8, 9] },
	{ cards: [1, 3, 9] },
	{ cards: [2, 8, 8] },
	{ cards: [4, 4, 8], afterMessageHeading: "Level 2", afterMessage: `Gunakan 4 kartu angka yang tersedia.\nPada level ini, operasi yang dapat digunakan hanya:\nPenjumlahan (+)\nPengurangan (−)\nPembagian (÷)\n` },
	{ cards: [1, 3, 4, 6], blacklist: '×' },
	{ cards: [1, 4, 5, 6], blacklist: '×' },
	{ cards: [1, 2, 6, 7], blacklist: '×' },
	{ cards: [1, 3, 7, 9], blacklist: '×' },
	{ cards: [1, 3, 8, 8], blacklist: '×' },
	{ cards: [2, 3, 4, 6], blacklist: '×' },
	{ cards: [2, 3, 8, 9], blacklist: '×' },
	{ cards: [3, 4, 5, 8], blacklist: '×' },
	{ cards: [3, 5, 6, 7], blacklist: '×' },
	{ cards: [3, 4, 8, 9], blacklist: '×' },
	{ cards: [4, 4, 5, 6], blacklist: '×' },
	{ cards: [5, 6, 7, 8], blacklist: '×' },
	{ cards: [6, 7, 8, 9], blacklist: '×' },
	{ cards: [2, 4, 5, 7], blacklist: '×' },
	{ cards: [6, 7, 9, 9], blacklist: '×', afterMessageHeading:"Level 3", afterMessage:`Pada level ini, kamu akan diberikan 4 kartu angka, diantaranya ada kartu desimal.\nOperasi yang dapat digunakan:\nPenjumlahan (+)\nPengurangan (−)\nPerkalian (×)\nPembagian (÷)`},
	{ cards: [13, 4, 3, 2] },
	{ cards: [10, 6, 4, 2] },
	{ cards: [10, 9, 3, 1] },
	{ cards: [11, 5, 8, 4] },
	{ cards: [11, 16, 5, 3] },
	{ cards: [13, 9, 5, 7] },
	{ cards: [12, 7, 8, 4] },
	{ cards: [10, 16, 3, 1] },
	{ cards: [12, 16, 4, 2] },
	{ cards: [10, 13, 9, 5] },
	{ cards: [10, 6, 4, 5] },
	{ cards: [10, 6, 4, 7] },
	{ cards: [10, 7, 5, 4] },
	{ cards: [13, 5, 3, 2] },
	{ cards: [15, 11, 5, 1] },
];
